const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94704020146"
const SESSION_ID = "PRABATH-MD~pVBFlaRL#GxTOKsygEuJKUqyp0VdTF6ZAuOGPbNQhqH0oE2ZQgJw"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
